Import('qtEnv')

env = qtEnv.Clone()
env.EnableQt4Modules(['QtCore','QtGui'])

source_files = Glob('*.cpp')
source_files.append(env.Qrc4('icons'))

env['QT4_QRCFLAGS'] = ['-name', 'othername']

env.Program('main', source_files)
