Import("qtEnv")

env = qtEnv.Clone()
env.EnableQt4Modules(['QtCore','QtGui'])
env['QT4_AUTOSCAN']=0

env.ExplicitMoc4('explicitly_moced_FromHeader.cpp','mocFromH.h')
env.ExplicitMoc4('explicitly_moced_FromCpp.strange_cpp_moc_prefix','mocFromCpp.cpp')

env.Program('main', Glob('*.cpp'))
