#!/usr/bin/env ork.python
################################################################################
# Terrain chunk renderer THREE-WAY A/B: SSBO-pull VS (+cull compute) vs taskless
# MESH SHADER, dispatched two ways.
#
# All three paths are generated by ONE source of truth — TerrainChunkVertexSource
# (gpu_chunk.py) — over ONE SSBO layout and ONE procedural heightfield:
#
#   vtx  (baseline) : cs_terrain_reset/cull/sort/finalize fill v_list + a
#                     VkDrawIndirectCommand; DrawIndirectEML pulls chunk^2*6
#                     non-indexed vertices, so every interior corner is decoded
#                     (and its heights[] tapped) ~6x.
#   mesh (direct)   : NO compute and NO indirect args. A FIXED workgroup grid
#                     (mesh_groups()) covers chunks x meshlets; each workgroup
#                     frustum-tests its own n x n-quad meshlet AABB and either
#                     emits nothing (SetMeshOutputsEXT(0,0)) or emits its (n+1)^2
#                     unique corners ONCE plus 2n^2 local-index triangles (n =
#                     gpu_chunk.DEFAULT_MESHLET_DIM, 8 -> 81 verts / 128 tris). A
#                     CULLED meshlet still costs a dispatched workgroup — which
#                     is why the all-culled view LOSES to the baseline on
#                     MoltenVK (mps^2 * nchunk workgroups that do nothing).
#   mesh (indirect) : ONE compaction dispatch (cs_terrain_meshcull) writes the
#                     compacted visible-chunk list AND the mesh draw's
#                     VkDrawMeshTasksIndirectCommandEXT{x=mps^2,y=visible,z=1};
#                     drawMeshTasksIndirect reads its grid from there, so the
#                     all-culled view dispatches literally nothing. Per-meshlet
#                     self-cull is retained inside the surviving chunks.
#
# Same triangulation, same winding, same per-vertex math => all three paths must
# rasterize the SAME image. This gate has two INDEPENDENT halves:
#
#   CORRECTNESS (trusted, unchanged methodology): pixel parity at 256x256 across
#     wide/near/away, measured against the BASELINE for every mesh path (a small
#     tolerance covers depth ties the mesh paths break differently — no sort). When
#     the device has the indirect draw entry it also asserts the compaction agrees
#     chunk-for-chunk with the baseline cull and that the all-culled view dispatches
#     literally NOTHING (y=0). Emits TESTVERDICT.
#
#   PERFORMANCE (reworked, owner spec 2026-07-24): GPU-honest per-frame wall-clock
#     at 2560x1280 offscreen. See the MESHPERF methodology block below. The prior
#     sub-ms perf_counter-sandwich-with-baseline-subtraction methodology (which
#     produced negative draw-times and an inverted "speedup") is REMOVED, not
#     deprecated.
#
# Fully synthetic: the heightfield is procedural and the shader is inline text —
# NO scene assets, NO asset cache, NO window. Runtime-gated on the real caps
# queries (ctx.supports_mesh_shader / .supports_mesh_shader_indirect): a device
# without VK_EXT_mesh_shader SKIPs clean, and one without the indirect draw entry
# runs the two-way, so the canary stays green fleet-wide.
################################################################################
#
# MESHPERF METHODOLOGY (binding, owner-specified 2026-07-24)
# ---------------------------------------------------------
# TIMING (GPU-honest, no sub-ms sandwiches):
#   In offscreen mode VkOffscreen::submit() does queueSubmit + fence->wait() per
#   frame (vulkan_offscreen.cpp). So host wall-clock wrapped around ONE full
#   frame() call — beginFrame .. draw .. endFrame — includes the whole GPU
#   submission AND the completion sync. We render N (>=300) full frames per leg,
#   collect the per-frame wall samples, and report mean / p50 / p95. No baseline
#   subtraction, no per-pass batching, no negative arithmetic.
#
# RASTER LOAD: perf legs run at 2560x1280 (--res) to lift real rasterization out
#   of the sub-ms noise floor. Correctness legs stay at 256x256 (--parity-res)
#   for speed; parity does not need the load.
#
# VSYNC-FREE / LOAD GUARD: before any timing a trivial calibration (empty clear
#   frames at perf res) must exceed --calib-min-fps (default 120). Offscreen is
#   unpaced by design; a rate below the floor means the box is paced or overloaded
#   — the gate then REFUSES to measure (prints reason=paced_or_overloaded and the
#   measured rate, emits ZERO MESHPERF lines). Under heavy box load this refusal
#   is the CORRECT outcome, not a bug; it does not redden the correctness verdict.
#
# SYMMETRIC ACCOUNTING: each path is timed doing exactly the per-frame work it
#   actually requires.
#     vtx      : full reset->cull->sort->finalize dispatch phase (submit+wait) THEN
#                the indirect draw frame — both round-trips inside the timed window.
#     mesh     : the fixed-grid mesh-task draw frame, NO compute.
#     mesh_ind : ONE compaction dispatch recorded INLINE onto the frame CB (dispatch +
#                producer->consumer barrier, NO separate submit/fence) THEN the indirect
#                mesh-task draw frame — one submit total. The compaction is mode 2's OWN
#                per-frame work, charged to the mesh_ind leg (never to vtx or direct mesh).
#   There are NO HUD/stats compute passes in this synthetic test (the CullStats HUD
#   passes live in the real terrain drawable, not here), so "HUD off" holds by
#   construction.
#
# RATIO is DEFINED as mesh_time / vtx_time  (values < 1.0 => mesh FASTER). No more
#   inverted "speedup". When the indirect leg runs, ratio_ind = mesh_ind / vtx (same
#   convention) is appended.
#
# HARD FAILS: any per-frame sample <= 0, or a non-positive mean/p95, aborts the
#   gate with reason=timing_artifact.
#
# OUTPUT: one machine-parseable line per vantage:
#   MESHPERF vantage=<v> res=<WxH> frames=<N> vtx_ms_mean=.. vtx_ms_p50=.. \
#            vtx_ms_p95=.. mesh_ms_mean=.. mesh_ms_p50=.. mesh_ms_p95=.. ratio=.. \
#            [mesh_ind_ms_mean=.. mesh_ind_ms_p50=.. mesh_ind_ms_p95=.. ratio_ind=..]
################################################################################
#
# MSAA PER-SAMPLE SURCHARGE LEG (added 2026-07-26)
# -----------------------------------------------
# WHAT IT MEASURES: the same mesh-vs-baseline comparison, run into a 1x target and
#   into an MSAA target (default 4x, --msaa-samples) at the SAME resolution and the
#   SAME vantage. Everything else — SSBO, shader text, camera, frame count — is held
#   identical, so the only variable is the render target's sample count.
#
# THE METRIC IS A RATIO OF RATIOS:
#   measured at 3840x2160 (--surcharge-res), NOT at the MESHPERF res: a per-SAMPLE defect only
#   separates from the per-frame submit floor once samples are the dominant work (SURCHARGE_W/H).
#     ratio_1x  = mesh_ms(1x)  / vtx_ms(1x)
#     ratio_Nx  = mesh_ms(Nx)  / vtx_ms(Nx)
#     surcharge = ratio_Nx / ratio_1x
#   surcharge > 1.0 means the mesh pipeline's MSAA cost multiplier exceeds the vertex
#   pipeline's over identical geometry. It is a RELATIVE measure and its denominator is
#   a real pipeline with its own MSAA behaviour — do NOT read it as "the mesh pipeline is
#   broken by X". At the SHIPPED meshlet 8 it measures 1.29 on NVIDIA/linux and 1.15 on
#   MoltenVK/M3 Ultra, and NEITHER absolute 1x->4x cost is alarming: mesh pays +0.85ms on
#   NVIDIA / +0.39ms on mac, its own vertex baseline +0.71ms / +0.46ms. The ratio exceeds 1
#   on both platforms mostly because the mesh path's 1x frame is the CHEAPER one, so the same
#   added sample work is a bigger multiple of it — which is why this leg is a per-platform
#   REGRESSION detector and not a defect proof.
#
# PER-PLATFORM REGRESSION FENCES (ONE rule, two recorded baselines):
#   Each platform records the MEAN surcharge it measures at the SHIPPED meshlet, and the leg
#   fences a symmetric band around it (SURCHARGE_BASELINE / SURCHARGE_BAND):
#     surcharge > baseline * 1.15  -> FAIL     — a real regression (engine, codegen or driver).
#     surcharge < baseline * 0.85  -> IMPROVED — the world moved the other way: re-measure and
#        re-record. It does NOT fail; an improvement must never redden the fleet.
#   The band swallows run-to-run noise on both platforms with room to spare — 3 sigma over six
#   consecutive full-gate runs is 12.5% of the mean on NVIDIA and 3.7% on MoltenVK.
#   NEITHER ARM IS A KNOWN-BAD CEILING ANY MORE. At meshlet 11 darwin measured 1.59-1.72 against
#   NVIDIA's 1.10-1.37, and the darwin arm was a known-bad ceiling that could only ask "did it get
#   WORSE?". The meshlet 11 -> 8 reshape erased that gap and inverted it — darwin now measures
#   LOWER than NVIDIA (1.148 vs 1.293) — so the magnitude the ceiling encoded is gone and both arms
#   are ordinary regression detectors. The runs behind that claim are in the RECORDED BASELINES
#   block below; update the baselines WITH the measurement that justifies the change.
#
# PROOF OF LOAD (two guards, because neither alone covers the configuration):
#   coverage : one captured frame per path into an RGBA8 MSAA target of the same sample
#     count — proves the multisampled render pass actually rasterizes this geometry.
#     RGBA8 because captureAsFormat cannot read a half-float attachment back.
#   clear-floor : each timed leg must cost >1.2x an empty (clear-only) frame on the SAME
#     target it is timed against — that is the guard that covers the RGBA16F targets.
#
# OUTPUT:
#   MESHMSAA vantage=<v> res=<WxH> fmt=<F> msaa=<N> frames=<N> vtx_ms_mean=.. mesh_ms_mean=.. ratio=..
#   MESHMSAA_SURCHARGE vantage=<v> res=<WxH> fmt=<F> msaa=<N> ratio_1x=.. ratio_Nx=.. \
#            surcharge=.. baseline=.. fence=.. platform=<darwin|other> result=<PASS|FAIL|IMPROVED>
#
# REPRODUCER MODES (upstream artifacts; NOT gates — they emit no TESTVERDICT):
#   --reproduce            per-sample mesh cost: msaa x resolution slope table for both
#                          pipelines. Run it on BOTH a MoltenVK box and a discrete-GPU box —
#                          the cross-platform pair is the evidence, one platform alone is not.
#   --reproduce-indirect   the MoltenVK indirect defect: drawMeshTasksIndirect against an
#                          SSBO-bound pipeline costs ~93ms/call in Release, independent
#                          of resolution, while the SAME pipeline drawn DIRECTLY over
#                          the same compacted list costs ordinary milliseconds. Sweeps
#                          draw-count (per-call linearity) and resolution.
################################################################################
#
# PAYLOAD CLIFF FENCE (added 2026-07-26) — ONE leg, two platform arms
# --------------------------------------------------------------------
# WHAT IT FENCES: the tile-contention regression class, permanently. Metal tile memory is
#   shared between the multisampled attachment set and the mesh stage's per-workgroup output
#   payload, and the mesh path's 4x cost falls off a CLIFF as the payload shrinks. The
#   shipped meshlet (gpu_chunk.DEFAULT_MESHLET_DIM, bound to the C++ kTerrainDefaultMeshletDim)
#   sits just under that cliff. Anything that re-crosses it — a payload bump, a codegen change
#   that re-fattens the workgroup output, a driver regression — turns this leg red.
#
# THE MEASUREMENT (identical on both platforms, so the arms differ only in the constant):
#   the SWEEP-PAYLOAD configuration — 3840x2160, 2x RGBA16F + Z32F (what ForwardPbrNodeImpl
#   multisamples), 4x, vantage `wide`, at the DEFAULT meshlet. Reported as mesh_ms, compared
#   against the RECORDED baseline for this platform:
#
#     ratio = mesh_ms / baseline_ms ;  FAIL when ratio > fence
#
# RECORDED BASELINES (measured jul26 on the tip that flipped the default 11 -> 8; 60 frames
# per leg, same config as above, mesh_ms mean):
#
#             platform            meshlet 11   meshlet 9   meshlet 8 (SHIPPED)   cliff 11->8
#   M3 Ultra / MoltenVK / darwin      4.529       4.596      1.613 / 1.675          2.81x
#   RTX 3090 / linux                  2.630       2.676      2.651 / 2.652          1.01x (FLAT)
#   (two meshlet-8 values = two independent runs; the pair is the run-to-run spread)
#
#   darwin arm  — THE CLIFF FENCE. baseline = the shipped payload's own cost (1.63ms class),
#     fence 1.60. The cliff value is 2.78x that baseline, so a re-crossing is caught with
#     enormous margin while run-to-run drift (measured 1.61..1.68 = 1.03x) is nowhere near it.
#     The fence is deliberately loose in RATIO terms because the absolute number sits at the
#     frame floor here — a clear-only frame on the same target costs 1.88ms, i.e. 1.15x the
#     baseline, so anything short of a real cliff cannot redden this.
#   non-darwin arm — THE NO-REGRESSION ASSERTION for the default flip. baseline = the cost of
#     the payload the flip REPLACED (meshlet 11, 2.63ms), fence 1.10. NVIDIA is payload-FLAT
#     over this range (8 vs 11 = 1.008), so the smaller shipped payload must cost the
#     discrete-GPU platform nothing; 1.10 is generous against noise and far tighter than any
#     real payload effect would be.
#
# Both constants are MEASURED, not guessed — update them WITH the measurement that justifies
# the change, and keep the table above in step.
#
# OUTPUT:
#   MESHCLIFF res=<WxH> fmt=<F> nattach=<N> msaa=<N> meshlet=<n> frames=<N> clear_ms=.. \
#             vtx_ms=.. mesh_ms=.. baseline_ms=.. ratio=.. fence=.. platform=<darwin|other> \
#             result=<PASS|FAIL>
################################################################################

import os
os.environ["PYTHONUNBUFFERED"] = "1"
import sys
sys.stdout.reconfigure(line_buffering=True)
import time
import argparse

# repo root = five levels up; prepend THIS checkout's scripts dir so ork.testing +
# the terrain generator resolve from the same tree as this test.
_ROOT = os.path.abspath(__file__)
for _ in range(5):
  _ROOT = os.path.dirname(_ROOT)
sys.path.insert(0, os.path.join(_ROOT, "obt.project", "scripts"))

import numpy

from orkengine import core   # core before lev2
from orkengine import lev2
from ork.testing import headless_app, verdict
from ork.hypergraph.dflow.terrain.gpu_chunk import TerrainChunkVertexSource, DEFAULT_MESHLET_DIM

tokens = core.CrcStringProxy()

DIM    = 1024     # heightfield grid (procedural)
EXTENT = 1000.0   # world meters per side
HMAX   = 90.0     # world meters of relief
CHUNK  = 128      # -> 8x8 chunks, ceil(128/meshlet)^2 meshlets each

# correctness (parity) render size — small on purpose; parity needs no raster load.
PARITY_W, PARITY_H = 256, 256
# perf render size — large enough that rasterization is well above the timer floor.
PERF_W, PERF_H     = 2560, 1280

# perf sampling
PERF_FRAMES   = 300     # full frames timed per (path, vantage) leg (owner: N >= 300)
PERF_WARMUP   = 8       # untimed warmup frames per leg (pipeline/pool warm)
CALIB_FRAMES  = 120     # empty clear frames used to measure the offscreen frame rate
CALIB_MIN_FPS = 120.0   # below this -> paced_or_overloaded, refuse to measure

# (name, eye, target, expect_geometry) — CORRECTNESS parity views (unchanged).
VIEWS = [
  ("wide", core.vec3(0.0, 420.0, 900.0),  core.vec3(0.0, 0.0, 0.0),      True),
  ("near", core.vec3(0.0, 130.0, 260.0),  core.vec3(0.0, 40.0, -140.0),  True),
  # camera BEHIND the field looking away: every chunk / every meshlet must cull.
  ("away", core.vec3(0.0, 420.0, 1400.0), core.vec3(0.0, 500.0, 3400.0), False),
]

# PERF vantages (owner spec): the three parity scales + a NEW ground-level mostly-
# culled vantage (camera near the ground at the south edge looking north across the
# field, so foreground ridges occlude most far chunks and everything behind the eye
# culls — the owner's real-world case).
PERF_VANTAGES = [
  ("wide",   core.vec3(0.0, 420.0, 900.0),  core.vec3(0.0, 0.0, 0.0)),
  ("near",   core.vec3(0.0, 130.0, 260.0),  core.vec3(0.0, 40.0, -140.0)),
  ("away",   core.vec3(0.0, 420.0, 1400.0), core.vec3(0.0, 500.0, 3400.0)),
  ("ground", core.vec3(0.0,   6.0,  470.0), core.vec3(0.0, 12.0, -500.0)),
]

# MSAA surcharge leg (see the header block). Short by design: it is a RATIO OF RATIOS, so
# it needs stable means, not deep statistics — and the 4x legs are the expensive ones on the
# platform that has the defect.
SURCHARGE_MSAA     = 4        # sample count the loaded leg renders into
SURCHARGE_FRAMES   = 120      # timed frames per (path, msaa) leg
SURCHARGE_VANTAGE  = "wide"   # whole field on screen: both paths draw real geometry
# The surcharge leg runs at 4K, NOT at the MESHPERF res, and owns its own knob. Rationale
# (measured on MoltenVK/M3-Ultra jul26): the defect is a per-SAMPLE cost, so it only separates
# from the per-frame submit floor once samples dominate the frame. Same content, same vantage:
# at 2560x1280 the surcharge reads 1.18, at 3840x2160 it reads 1.68. The lower res is not wrong,
# it is diluted — measure the per-sample defect where samples are the work.
SURCHARGE_W, SURCHARGE_H = 3840, 2160
SURCHARGE_FORMAT = "RGBA16F"  # what ForwardPbrNodeImpl multisamples (RGBA32F is too heavy);
                              #  measuring RGBA8 would not be measuring the shipped configuration
# RECORDED BASELINES (re-measured jul26 AT THE SHIPPED MESHLET 8; 3840x2160 RGBA16F 4x, vantage
# wide, 120 frames/leg). Six consecutive FULL gate runs per platform, surcharge per run:
#
#   NVIDIA 3090 / linux   1.2436 1.2567 1.3889 1.2660 1.2819 1.3204   mean 1.293  sd 0.054  3sd 12.5%
#   M3 Ultra / MoltenVK   1.1511 1.1586 1.1543 1.1424 1.1583 1.1212   mean 1.148  sd 0.014  3sd  3.7%
#
#   -> FAIL fence  = mean * 1.15 : 1.487 NVIDIA (was 1.60) / 1.320 darwin (was a 1.95 ceiling)
#      IMPROVED at = mean * 0.85 : 1.099 NVIDIA / 0.976 darwin — clear of the whole measured band on
#      both, so IMPROVED is a rare event again. It had become the STEADY STATE on darwin: against the
#      old 1.45 threshold the shipped shape tripped IMPROVED on every single run.
#
#   HELD OUT (five more full runs per platform, AT these fences, after the constants were set —
#   the fences were NOT fitted to them): NVIDIA 1.2518-1.3781, darwin 1.1504-1.1824, all PASS.
#   Over all eleven runs 3 sigma is 11.6% of the mean on NVIDIA and 3.9% on darwin, both still
#   inside the band; the worst single run sits 7% (NVIDIA) / 12% (darwin) under its fence.
#
# PROVENANCE — WHY THE OLD CONSTANTS MOVED: 1.60 / 1.95 / 1.45 were measured at meshlet 11 (NVIDIA
# 1.10-1.37, darwin 1.59-1.72 there). This leg always runs at the SHIPPED payload, so the default
# flip 11 -> 8 moved the SUBJECT of the measurement, not the methodology. Post-flip the darwin
# ceiling sat ~1.7x above the value it was fencing and had no detection power left; that is what
# forced this re-fence, and both arms are ordinary regression fences now (see the header block).
#
# WHY FULL GATE RUNS ARE THE CALIBRATION: the surcharge leg cannot run without the MESHPERF battery
# ahead of it (main() gates both on --no-perf), so the clock/thermal state these numbers were taken
# in IS the state the gate always measures in. A hand-run "leg alone" number — at meshlet 11 a full
# 0.27 higher on NVIDIA — is not a configuration the fence has to cover. Preceding load is the
# dominant noise source here: NVIDIA's 1.3889 outlier is a fast 1x leg (vtx 1.58ms vs a 2.0ms
# typical), not a slow 4x one, and it is what sizes the band.
SURCHARGE_BASELINE = {"darwin": 1.148, "other": 1.293}  # recorded mean at the shipped meshlet
SURCHARGE_BAND     = 0.15   # FAIL above baseline*(1+band); IMPROVED (nag, never red) below *(1-band)

# ---- tile-contention sweeps (manual artifacts, not gates) --------------------------------
# Hypothesis under test: the real forward pass's mesh cost cliff at 4x comes from tile memory
# shared between the multisampled attachment set and the Metal mesh stage's per-workgroup output
# payload. Two axes, measured independently: attachment weight (fixed payload) and payload size
# (fixed attachment set).
FMT_BYTES        = {"RGBA8": 4, "RGBA16F": 8}
# the SHIPPED payload, from gpu_chunk (which is itself bound to the C++ kTerrainDefaultMeshletDim).
# Never a literal here: the cliff fence below is only meaningful if this test and the engine agree
# on what "the default" is.
SHIPPED_MESHLET  = DEFAULT_MESHLET_DIM
# (fmt, nattach): single 8-bit -> single half-float -> the forward pass's 2xMRT half-float set
SWEEP_ATTACH_SETS = (("RGBA8", 1), ("RGBA16F", 1), ("RGBA16F", 2))
# 9 and 8 bracket the measured cliff — keep both in the artifact so a re-measure re-locates it.
SWEEP_MESHLETS    = (11, 9, 8, 6, 4)
SWEEP_FRAMES      = 40

# ---- payload cliff fence (GATE LEG; see the PAYLOAD CLIFF FENCE block in the header) -----
# The measurement rides the sweep configuration: SURCHARGE_W/H, 2x RGBA16F + Z32F, SURCHARGE_MSAA,
# vantage `wide`, at the SHIPPED meshlet.
CLIFF_FRAMES   = 60
CLIFF_NATTACH  = 2
# RECORDED baselines (jul26, mesh_ms mean at that configuration) and their fences. Per platform:
# darwin fences the shipped payload against the CLIFF it sits under; elsewhere it fences the
# default flip against the payload it replaced. Measured constants — see the header table.
CLIFF_BASELINE_MS = {"darwin": 1.63,  "other": 2.63}
CLIFF_FENCE       = {"darwin": 1.60,  "other": 1.10}

# reproducer sweeps (manual artifacts, not gates)
REPRO_FRAMES     = 40
REPRO_RESOLUTIONS = ((640, 360), (2560, 1280), (3840, 2160))
REPRO_MSAA_LEVELS = (1, 2, 4)
REPRO_DRAWCOUNTS  = (1, 2, 4)

PARITY_MIN_EXACT = 1.0     # byte-exact. Was 0.995 to absorb depth ties the unsorted mesh
                           #  paths broke differently; the meshcull-inlined near-to-far sort
                           #  closed them — measured exact=1.0000 on all nine legs on BOTH
                           #  NVIDIA and MoltenVK (jul26) — so anything less is a regression.
PARITY_MAX_MEAN  = 1.0     # mean |delta| over RGB, in 8-bit levels
MIN_COVERAGE     = 0.05    # a "geometry expected" view must fill at least this much

################################################################################

def synth_heights(dim, hmax):
  """Procedural heightfield in TRUE METERS (ridges + a central dome) — the SSBO's
  heights[] contract. No asset, no bake, no disk."""
  xs = (numpy.arange(dim, dtype=numpy.float32) + 0.5) / float(dim) - 0.5
  X, Z = numpy.meshgrid(xs, xs, indexing="xy")
  h = (0.55
       + 0.25 * numpy.sin(X * 14.0) * numpy.cos(Z * 11.0)
       + 0.20 * numpy.exp(-((X * 2.4) ** 2 + (Z * 2.4) ** 2)))
  return (numpy.clip(h, 0.0, 1.0) * hmax).astype(numpy.float32).reshape(-1)

################################################################################

MRT_BLOCK = """
////////////////////////////////////////
// MRT variant (attachment-weight sweep only): the SAME geometry stages feeding a two-output
// fragment stage, so a 2xMRT target has every attachment actually written.
fragment_interface fif_terrain_mrt : vif_terrain {
  outputs { layout(location = 0) vec4 out_clr; layout(location = 1) vec4 out_aux; }
}
fragment_shader ps_terrain_mrt : fif_terrain_mrt {
  out_clr = frg_clr;
  out_aux = vec4(frg_clr.yzx, 1.0);
}
technique tek_vtx_mrt {
  fxconfig = fxcfg_default;
  pass p0 { vertex_shader = vs_terrain; fragment_shader = ps_terrain_mrt; state_block = default; }
}
technique tek_mesh_mrt {
  fxconfig = fxcfg_default;
  pass p0 { mesh_shader = ms_terrain; fragment_shader = ps_terrain_mrt; state_block = default; }
}
"""


def build_shader(vs, mrt=False):
  """One fxv2 program carrying ALL THREE techniques + both cull computes. Every geometry
  line comes from the generator; only the interfaces, the shade helper and the technique
  declarations are local to this test — so a divergence between the paths can only come
  from the engine, never from hand-written shaders drifting apart. The two mesh stages
  differ ONLY in the generator's chunk decode (dense grid vs compacted list)."""
  return """
fxconfig fxcfg_default {}
////////////////////////////////////////
storage_interface sif_ptex_vtx (descriptor_set 0) {
  buffer layout(std430) ptex_vtx_data {
%(LAYOUT)s
  };
}
libblock lib_terr {
%(LIB)s
  // SHARED by both paths: identical inputs must produce identical pixels.
  vec4 terr_shade(vec3 nrm, vec2 uv) {
    float lam = clamp(dot(normalize(nrm), normalize(vec3(0.4, 0.85, 0.3))), 0.0, 1.0);
    return vec4(lam, 0.35 + 0.5 * uv.x, 0.25 + 0.5 * uv.y, 1.0);
  }
}
////////////////////////////////////////
vertex_interface vif_terrain : sif_ptex_vtx {
  outputs { vec4 frg_clr; }
}
%(MESHIFACE)s
fragment_interface fif_terrain : vif_terrain {
  outputs { layout(location = 0) vec4 out_clr; }
}
////////////////////////////////////////
vertex_shader vs_terrain : vif_terrain : lib_terr {
%(VSBODY)s
  gl_Position = c_vp * position;
  frg_clr = terr_shade(normal, uv0);
}
////////////////////////////////////////
mesh_shader ms_terrain : extension(GL_EXT_mesh_shader) : vif_terrain_mesh : lib_terr {
%(MESHBODY)s
}
////////////////////////////////////////
mesh_shader ms_terrain_ind : extension(GL_EXT_mesh_shader) : vif_terrain_mesh : lib_terr {
%(MESHBODYIND)s
}
////////////////////////////////////////
// mode-1 DIRECT-SIZED variant: the compacted decode WITH the over-dispatch capacity guard
// (gl_WorkGroupID.y >= v_count -> emit nothing). The C++ drawable dispatches this over a CPU-sized
// grid whose y may EXCEED v_count; the guard makes those stale-slot workgroups cheap+correct. Here
// it is dispatched over the FULL nchunk grid (maximum over-dispatch) to prove byte-identity anyway.
mesh_shader ms_terrain_dir : extension(GL_EXT_mesh_shader) : vif_terrain_mesh : lib_terr {
%(MESHBODYDIR)s
}
////////////////////////////////////////
fragment_shader ps_terrain : fif_terrain {
  out_clr = frg_clr;
}
////////////////////////////////////////
technique tek_vtx {
  fxconfig = fxcfg_default;
  pass p0 { vertex_shader = vs_terrain; fragment_shader = ps_terrain; state_block = default; }
}
technique tek_mesh {
  fxconfig = fxcfg_default;
  pass p0 { mesh_shader = ms_terrain; fragment_shader = ps_terrain; state_block = default; }
}
technique tek_mesh_ind {
  fxconfig = fxcfg_default;
  pass p0 { mesh_shader = ms_terrain_ind; fragment_shader = ps_terrain; state_block = default; }
}
technique tek_mesh_dir {
  fxconfig = fxcfg_default;
  pass p0 { mesh_shader = ms_terrain_dir; fragment_shader = ps_terrain; state_block = default; }
}
////////////////////////////////////////
%(MRT)s
////////////////////////////////////////
%(COMPUTE)s
""" % dict(MRT=(MRT_BLOCK if mrt else ""),
           LAYOUT=_indent(vs.layout, 4),
           LIB=_indent(vs.lib, 2),
           MESHIFACE=vs.mesh_interface(outputs="vec4 frg_clr;"),
           VSBODY=_indent(vs.vs_body, 2),
           MESHBODY=_indent(vs.mesh_body(mvp="c_vp", compacted=False,
                                         varying_writes="frg_clr[$V] = terr_shade(normal, uv0);"), 2),
           MESHBODYIND=_indent(vs.mesh_body(mvp="c_vp", compacted=True,
                                            varying_writes="frg_clr[$V] = terr_shade(normal, uv0);"), 2),
           MESHBODYDIR=_indent(vs.mesh_body(mvp="c_vp", compacted=True, guard_capacity=True,
                                            chunk_cull=False,
                                            varying_writes="frg_clr[$V] = terr_shade(normal, uv0);"), 2),
           COMPUTE=vs.compute)


def _indent(text, n):
  pad = " " * n
  return "\n".join(pad + ln for ln in text.strip().splitlines())

################################################################################

class Target:
  """One offscreen RtGroup at a given size (depth-tested; a heightfield hides itself
  behind its own ridges). The A/B keeps two: a small parity target and a large perf
  target, both fed by the SAME SSBO + material. msaa is a literal hw sample count; the
  multisample attachments resolve down to the sampled image, so capture still works."""

  def __init__(self, ctx, w, h, msaa=1, fmt="RGBA8", nattach=1):
    self.w, self.h = int(w), int(h)
    self.msaa = int(msaa)
    self.fmt  = fmt
    self.nattach = int(nattach)
    self.rtg = lev2.RtGroup(ctx, self.w, self.h, self.msaa)
    # fmt matters for the MSAA legs: ForwardPbrNodeImpl drops its color MRTs to RGBA16F the
    # moment MSAA is on (RGBA32F is too heavy to multisample), so a surcharge measured on RGBA8
    # would not be measuring the format the engine actually multisamples.
    # nattach > 1 reproduces the forward pass's MRT set; every attachment must be WRITTEN by the
    # fragment stage (the _mrt techniques), or the tile traffic under test is not being paid.
    self.rtbs = []
    for _ in range(self.nattach):
      rtb = self.rtg.createBuffer(getattr(tokens, fmt), tokens.color)
      rtb.clearColor = core.vec4(0, 0, 0, 1)
      self.rtbs.append(rtb)
    self.rtb = self.rtbs[0]
    self.rtg.createDepthBuffer(tokens.Z32F, True)
    self.rtg.autoclear = True

  @property
  def bytes_per_px(self):
    """Attachment weight per pixel INCLUDING samples and the Z32F depth attachment — the
    x-axis of the tile-contention sweep."""
    return (FMT_BYTES[self.fmt] * self.nattach + 4) * self.msaa

################################################################################

class TerrainAB:
  """All three draw paths over ONE SSBO + ONE material, rendered into offscreen RtGroups."""

  def __init__(self, app, parity_wh, perf_wh, want_indirect, meshlet=SHIPPED_MESHLET, mrt=False):
    self.app = app
    self.ctx = app.ctx
    self.want_indirect = want_indirect
    # mesh + mesh_indirect FORCED (never env-derived): this gate owns its own three-way
    # comparison and must produce the same program on a machine with the toggle set either way.
    # mesh_cull_chunk FORCED meshlet too (the DEFAULT granularity) so an ambient ORKID_TERRAIN_MESHCULL
    # can't perturb the parity legs — same reproducibility principle as the mesh flags.
    self.vs = TerrainChunkVertexSource(dim=DIM, extent_m=EXTENT, chunk=CHUNK, meshlet=int(meshlet),
                                       mesh=True, mesh_indirect=True, mesh_cull_chunk=False)
    fxi = self.ctx.FXI

    ############################################
    # the SSBO: heights + u_dim + the global height bounds. chunk_y[] is left zeroed —
    # it feeds the HZB occlusion test only, and c_misc.y = 0 disables that.
    ############################################
    self.heights = synth_heights(DIM, HMAX)
    self.ssbo = fxi.createShaderStorageBufferWithLength(self.vs.TOTAL)
    fxi.copyDataIntoShaderStorageBuffer(self.heights, self.ssbo, self.vs.HEIGHTS_OFF)
    self.vs.upload_dim(fxi, self.ssbo)
    fxi.copyDataIntoShaderStorageBuffer(
        numpy.array([float(self.heights.min()), float(self.heights.max())], dtype=numpy.float32),
        self.ssbo, self.vs.YB_OFF)

    ############################################
    # material + the three pipelines (technique forced per draw)
    ############################################
    self.mtl = lev2.FreestyleMaterial()
    self.mtl.gpuInitFromShaderText(self.ctx, "terrain_ab", build_shader(self.vs, mrt=mrt))
    self.mtl.rasterstate.culltest = tokens.OFF        # both paths share one winding; not under test
    self.mtl.rasterstate.depthtest = tokens.LEQUALS   # heightfield self-occludes

    # over-dispatch grid the mode-1 direct-sized leg walks: the FULL chunk grid (worst-case
    # over-dispatch), so slots [vis, nchunk) all read stale v_list entries the guard must zero.
    self.dir_capacity = self.vs.nchunk

    paths = [("vtx", "tek_vtx"), ("mesh", "tek_mesh"),
             ("mesh_ind", "tek_mesh_ind"), ("mesh_dir", "tek_mesh_dir")]
    if mrt:
      paths += [("vtx_mrt", "tek_vtx_mrt"), ("mesh_mrt", "tek_mesh_mrt")]
    self.tek = {}
    for path, tekname in paths:
      tek = self.mtl.shader.technique(tekname)
      assert tek, "technique %s not found" % tekname
      self.tek[path] = tek
    self.pipe = {}
    for name, tek in self.tek.items():
      permu = lev2.FxPipelinePermutation()
      permu.rendermodel = "CUSTOM"
      permu.technique = tek
      pipe = self.mtl.fxcache.findPipeline(permu)
      assert pipe, "no pipeline for %s" % name
      pipe.bindStorage(self.mtl.storage("sif_ptex_vtx"), self.ssbo)
      self.pipe[name] = pipe

    self.cs = {}
    for (cs_name, _gx, _gy, _gz) in self.vs.compute_passes() + self.vs.mesh_compute_passes():
      shader = self.mtl.computeShader(cs_name)
      assert shader, "compute shader %s missing" % cs_name
      self.cs[cs_name] = shader

    self.groups = self.vs.mesh_groups()

    ############################################
    # the two offscreen targets (parity + perf)
    ############################################
    self.parity = Target(self.ctx, *parity_wh)
    self.perf   = Target(self.ctx, *perf_wh)
    # (w,h,msaa) -> Target, built on demand by the MSAA surcharge leg and the reproducers.
    # Kept alive for the whole run so a leg never pays target creation inside a timed window.
    self._targets = {(self.perf.w, self.perf.h, 1, "RGBA8", 1): self.perf,
                     (self.parity.w, self.parity.h, 1, "RGBA8", 1): self.parity}

  ##############################################

  def target(self, w, h, msaa, fmt="RGBA8", nattach=1):
    """Memoized offscreen target. Requesting a sample count the device cannot do raises
    out of the RtGroup ctor (pyext refuses to quietly hand back a quieter target)."""
    key = (int(w), int(h), int(msaa), fmt, int(nattach))
    tgt = self._targets.get(key)
    if tgt is None:
      tgt = Target(self.ctx, w, h, msaa, fmt, nattach)
      self._targets[key] = tgt
    return tgt

  ##############################################

  def set_view(self, eye, tgt, target):
    """Write the CamBlk the cull compute AND all draw paths read (c_vp is the only
    clip-space matrix in play — no uniform blocks, so the paths cannot disagree).
    Aspect is taken from the target being rendered, so culling matches its viewport."""
    proj = core.mtx4.perspective(45.0 * 3.14159265 / 180.0,
                                 float(target.w) / float(target.h), 1.0, 4000.0)
    view = core.mtx4.lookAt(eye, tgt, core.vec3(0, 1, 0))
    vp = proj * view   # orkid operator* is rtol; matches CameraMatrices::multiply_ltor(v,p)
    fxi = self.ctx.FXI
    fxi.copyDataIntoShaderStorageBuffer(numpy.array(vp, dtype=numpy.float32).reshape(-1),
                                        self.ssbo, self.vs.CAM_OFF)
    fxi.copyDataIntoShaderStorageBuffer(numpy.array(vp.inverse, dtype=numpy.float32).reshape(-1),
                                        self.ssbo, self.vs.CAM_OFF + 64)
    fxi.copyDataIntoShaderStorageBuffer(numpy.array([eye.x, eye.y, eye.z, 1.0], dtype=numpy.float32),
                                        self.ssbo, self.vs.CAM_OFF + 128)
    # misc.x = CullFrustumScale 1.0 (exact frustum), misc.yzw = 0 -> HZB occlusion off
    fxi.copyDataIntoShaderStorageBuffer(numpy.array([1.0, 0.0, 0.0, 0.0], dtype=numpy.float32),
                                        self.ssbo, self.vs.CAM_OFF + 144)

  def _dispatch(self, passes):
    """One dispatch phase over `passes` (endDispatchPhase submits AND waits, exactly as
    ComputeDrawable::onPreRender does), storageBarrier between."""
    ci = self.ctx.CI
    ci.beginDispatchPhase()
    for i, (cs_name, gx, gy, gz) in enumerate(passes):
      shader = self.cs[cs_name]
      ci.bindStorageBuffer(shader, 0, self.ssbo)
      ci.bindStorageBuffer(shader, 1, self.ssbo)  # sif_hzb stand-in; misc.y == 0 -> never read
      ci.dispatch(shader, gx, gy, gz)
      if (i + 1) < len(passes):
        ci.storageBarrier()
    ci.endDispatchPhase()

  def run_compute(self):
    """The baseline's per-view GPU work: reset -> cull -> sort -> finalize."""
    self._dispatch(self.vs.compute_passes())

  def run_meshcull_inline(self):
    """The indirect path's per-view GPU work: ONE compaction dispatch that fills v_list and writes
    the mesh draw command — recorded INLINE onto the frame's primary command buffer (dispatch +
    producer->consumer barrier), so it rides the ONE frame submit instead of a dedicated compute
    submit+fence-wait (the whole per-frame cost on MoltenVK). Must be called AFTER beginFrame() and
    BEFORE the render pass (rtGroupPush) — the compute-legal, outside-a-render-pass point.
    Correctness now comes from the barrier, NOT from a fence draining the compute first."""
    ci = self.ctx.CI
    for (cs_name, gx, gy, gz) in self.vs.mesh_compute_passes():
      shader = self.cs[cs_name]
      ci.bindStorageBuffer(shader, 0, self.ssbo)
      ci.bindStorageBuffer(shader, 1, self.ssbo)  # sif_hzb stand-in; misc.y == 0 -> never read
      ci.dispatchInline(shader, gx, gy, gz)

  def visible_chunks(self):
    """The cull funnel the last cull pass wrote: (visible, frustum-pass, total)."""
    import struct
    m = self.ctx.FXI.mapStorageBuffer(self.ssbo, self.vs.VIS_OFF, 16, tokens.READ_ONLY)
    vals = struct.unpack("<4I", bytes(m.data)[:16])
    self.ctx.FXI.unmapStorageBuffer(m)
    return vals[0], vals[1], vals[3]

  def mesh_args(self):
    """The VkDrawMeshTasksIndirectCommandEXT the compaction pass published: (x, y, z). y IS the
    dispatched workgroup rows — 0 means the GPU issues no mesh work at all."""
    import struct
    m = self.ctx.FXI.mapStorageBuffer(self.ssbo, self.vs.ARGS_OFF, 12, tokens.READ_ONLY)
    vals = struct.unpack("<3I", bytes(m.data)[:12])
    self.ctx.FXI.unmapStorageBuffer(m)
    return vals

  ##############################################

  def frame(self, path, target, capbuf=None, draw=True, draws=1):
    """One FULL offscreen frame doing exactly the per-frame work `path` requires. In
    offscreen mode endFrame() submits AND fence-waits, so the caller's wall-clock around
    this call is the GPU-honest per-frame cost.

    vtx      : reset/cull/sort/finalize dispatch (submit+wait) THEN one indirect draw frame.
    mesh     : one fixed-grid mesh-task draw frame, NO compute.
    mesh_ind : ONE compaction dispatch recorded INLINE onto the frame CB (dispatch + barrier, no
               separate submit/fence) THEN an indirect mesh-task draw frame — one submit total; the
               compaction is this path's OWN per-frame work, charged to it.
    draw=False renders an EMPTY (clear-only) frame — used for the calibration guard;
    it runs no compute regardless of path.
    draws>1 repeats the SAME draw call inside the one render pass (identical state, no extra
    compute) — the per-call slope the indirect reproducer measures."""
    ctx = self.ctx
    # "<path>_mrt" is the SAME draw path against the two-output fragment stage (attachment sweep):
    # the per-frame work is chosen by the base path, the pipeline/technique by the full name.
    base = path[:-4] if path.endswith("_mrt") else path
    if draw and base == "vtx":
      self.run_compute()
    ctx.beginFrame()
    if draw and base in ("mesh_ind", "mesh_dir"):
      # compaction recorded INLINE onto the just-begun frame CB (outside the render pass), so the
      # whole leg is ONE submit — the fence that was mode 2's entire MoltenVK cost is gone. mesh_dir
      # (mode-1 direct-sized) consumes the SAME compacted v_list, just via a CPU-sized direct grid.
      self.run_meshcull_inline()
    ctx.FBI.rtGroupPush(target.rtg)
    ctx.FBI.rtGroupClear(target.rtg)
    if draw:
      RCFD = lev2.RenderContextFrameData(ctx)
      RCID = lev2.RenderContextInstData(RCFD)
      RCID.forceTechnique(self.tek[path])
      RCID.genMatrix(lambda: core.mtx4())
      pipe = self.pipe[path]
      for _ in range(draws):
        if base == "vtx":
          pipe.wrappedDrawCall(RCID, lambda: ctx.GBI.drawIndirect(
              args=self.ssbo, primtype=tokens.TRIANGLES, args_offset=self.vs.ARGS_OFF))
        elif base == "mesh_ind":
          # the whole grid — including the all-culled y=0 — comes from the SSBO
          pipe.wrappedDrawCall(RCID, lambda: ctx.GBI.drawMeshTasksIndirect(
              args=self.ssbo, args_offset=self.vs.ARGS_OFF))
        elif base == "mesh_dir":
          # mode-1 DIRECT-SIZED: a DIRECT drawMeshTasks over a CPU-sized grid (here the full nchunk
          # over-dispatch). The capacity guard zeroes the stale slots [v_count, nchunk). NEVER indirect.
          pipe.wrappedDrawCall(RCID, lambda: ctx.GBI.drawMeshTasks(
              self.groups[0], self.dir_capacity, 1))
        else:
          gx, gy, gz = self.groups
          pipe.wrappedDrawCall(RCID, lambda: ctx.GBI.drawMeshTasks(gx, gy, gz))
    future = ctx.FBI.captureAsFormat(target.rtb, capbuf, "RGBA8") if capbuf is not None else None
    ctx.FBI.rtGroupPop()
    ctx.endFrame()
    return future

  def capture(self, path, target):
    capbuf = lev2.CaptureBuffer()
    future = self.frame(path, target, capbuf=capbuf)
    frames = 0
    while not future.is_ready:
      self.app.run_frames(1)
      frames += 1
      assert frames < 600, "terrain %s capture never became ready" % path
    return numpy.array(capbuf, dtype=numpy.uint8).reshape(capbuf.height, capbuf.width, 4)

  ##############################################

  def calibration_fps(self, target, frames=CALIB_FRAMES, warmup=8):
    """Trivial empty-clear frames at perf res -> measured offscreen frame rate. Offscreen
    is unpaced; a low rate means paced/overloaded. Returns frames-per-second (float)."""
    for _ in range(warmup):
      self.frame("mesh", target, draw=False)
    t0 = time.perf_counter()
    for _ in range(frames):
      self.frame("mesh", target, draw=False)
    dt = time.perf_counter() - t0
    return float(frames) / dt if dt > 0.0 else 0.0

  def time_leg(self, path, target, frames=PERF_FRAMES, warmup=PERF_WARMUP, draws=1,
               draw_only_clear=False):
    """N full frames, one per-frame wall sample each (each includes the offscreen fence
    wait). Returns (mean_ms, p50_ms, p95_ms, min_ms). No baseline subtraction.
    draw_only_clear times EMPTY frames on the same target — the floor a real leg must beat."""
    do_draw = not draw_only_clear
    for _ in range(warmup):
      self.frame(path, target, draw=do_draw, draws=draws)
    samples = numpy.empty(frames, dtype=numpy.float64)
    for i in range(frames):
      t0 = time.perf_counter()
      self.frame(path, target, draw=do_draw, draws=draws)
      samples[i] = (time.perf_counter() - t0) * 1000.0
    return (float(samples.mean()),
            float(numpy.percentile(samples, 50)),
            float(numpy.percentile(samples, 95)),
            float(samples.min()))

################################################################################

def compare(a, b):
  """(exact-match fraction, mean |delta| over RGB, coverage of a, coverage of b)."""
  ra, rb = a[..., :3].astype(numpy.int16), b[..., :3].astype(numpy.int16)
  exact = float((ra == rb).all(axis=2).mean())
  mean = float(numpy.abs(ra - rb).mean())
  cov_a = float((ra.sum(axis=2) > 0).mean())
  cov_b = float((rb.sum(axis=2) > 0).mean())
  return exact, mean, cov_a, cov_b

################################################################################

def parse_args():
  ap = argparse.ArgumentParser(add_help=False)
  ap.add_argument("--res", default="%dx%d" % (PERF_W, PERF_H),
                  help="perf-leg offscreen resolution WxH (default 2560x1280)")
  ap.add_argument("--parity-res", default="%dx%d" % (PARITY_W, PARITY_H),
                  help="correctness-leg resolution WxH (default 256x256)")
  ap.add_argument("--frames", type=int, default=PERF_FRAMES,
                  help="full frames timed per (path,vantage) leg (default 300)")
  ap.add_argument("--calib-frames", type=int, default=CALIB_FRAMES,
                  help="empty frames used to measure the offscreen frame rate")
  ap.add_argument("--calib-min-fps", type=float, default=CALIB_MIN_FPS,
                  help="calibration floor; below this -> paced_or_overloaded (default 120)")
  ap.add_argument("--no-perf", action="store_true",
                  help="run only the correctness legs (skip all MESHPERF work)")
  # ---- MSAA per-sample surcharge leg ----
  ap.add_argument("--msaa-samples", type=int, default=SURCHARGE_MSAA,
                  help="sample count for the loaded surcharge leg (default 4)")
  ap.add_argument("--surcharge-frames", type=int, default=SURCHARGE_FRAMES,
                  help="timed frames per (path,msaa) surcharge leg (default 60)")
  ap.add_argument("--surcharge-vantage", default=SURCHARGE_VANTAGE,
                  help="which PERF_VANTAGES entry the surcharge leg uses (default wide)")
  ap.add_argument("--surcharge-format", default=SURCHARGE_FORMAT, choices=("RGBA8", "RGBA16F"),
                  help="color format for the surcharge/reproducer targets (default RGBA16F — the "
                       "format ForwardPbrNodeImpl actually multisamples)")
  ap.add_argument("--surcharge-res", default="%dx%d" % (SURCHARGE_W, SURCHARGE_H),
                  help="surcharge-leg resolution WxH (default 3840x2160 — the per-sample defect "
                       "only separates from the submit floor when samples dominate the frame)")
  ap.add_argument("--cliff-frames", type=int, default=CLIFF_FRAMES,
                  help="timed frames per leg in the payload cliff fence (default %d)" % CLIFF_FRAMES)
  ap.add_argument("--no-cliff", action="store_true",
                  help="skip the payload cliff fence leg")
  ap.add_argument("--no-surcharge", action="store_true",
                  help="skip the MSAA per-sample surcharge leg")
  # ---- upstream reproducers (not gates) ----
  ap.add_argument("--reproduce", action="store_true",
                  help="MoltenVK artifact: mesh per-sample surcharge slope table (msaa x resolution)")
  ap.add_argument("--reproduce-indirect", action="store_true",
                  help="MoltenVK artifact: drawMeshTasksIndirect per-call cost (draw-count + res sweep)")
  ap.add_argument("--reproduce-frames", type=int, default=REPRO_FRAMES,
                  help="timed frames per reproducer leg (default 40)")
  # ---- tile-contention sweeps (not gates) ----
  ap.add_argument("--sweep-attach", action="store_true",
                  help="tile-contention axis (a): mesh:vtx surcharge vs attachment weight")
  ap.add_argument("--sweep-payload", action="store_true",
                  help="tile-contention axis (b): mesh cost vs per-workgroup output payload")
  ap.add_argument("--sweep-frames", type=int, default=SWEEP_FRAMES,
                  help="timed frames per sweep leg (default 40)")
  ap.add_argument("--sweep-res", default="%dx%d" % (SURCHARGE_W, SURCHARGE_H),
                  help="sweep resolution WxH (default 3840x2160 — where samples are the work)")
  ap.add_argument("--sweep-meshlets", default=",".join(str(m) for m in SWEEP_MESHLETS),
                  help="payload-sweep meshlet quad dimensions, comma separated (default 11,8,6,4)")
  ap.add_argument("--meshlet", type=int, default=SHIPPED_MESHLET,
                  help="meshlet quad dimension the correctness/perf legs build (default 11 — the "
                       "shipped shape; a smaller value proves a reshaped payload is still exact)")
  ap.add_argument("--sweep-payload-attach", type=int, default=2,
                  help="attachment count the payload sweep renders into (default 2 — the "
                       "forward pass's MRT set)")
  # tolerate args injected by the runner
  args, _unknown = ap.parse_known_args()
  return args


def _wh(s):
  w, h = s.lower().split("x")
  return int(w), int(h)

################################################################################

def run_correctness(ab):
  """Pixel-parity + all-culled proof at parity res, measured against the BASELINE for
  every mesh path. When the device has the indirect draw entry, also asserts the
  compaction agrees chunk-for-chunk with the baseline cull, publishes the mesh grid
  command exactly, and dispatches NOTHING on an all-culled view. Returns (fails, rows)."""
  fails = []
  rows = []
  for (name, eye, tgt, expect_geo) in VIEWS:
    ab.set_view(eye, tgt, ab.parity)
    img_vtx = ab.capture("vtx", ab.parity)
    vis, frus, total = ab.visible_chunks()      # baseline cull funnel (read before mesh_ind overwrites)
    img_msh = ab.capture("mesh", ab.parity)     # direct mesh: NO compute -> VIS unchanged
    exact, mean, cov_v, cov_m = compare(img_vtx, img_msh)

    # mode-1 DIRECT-SIZED: compacted decode + capacity guard, over-dispatched over the FULL nchunk
    # grid. Must be byte-identical to the baseline (the guard zeroes stale slots; rendered slots are
    # the same compacted chunks). Runs its OWN inline compaction in frame(). Available whenever the
    # device has mesh shaders (direct draw needs no indirect-draw entry).
    img_dir = ab.capture("mesh_dir", ab.parity)
    ex_d, mean_d, _cvd, cov_d = compare(img_vtx, img_dir)
    if ex_d < PARITY_MIN_EXACT:
      fails.append("%s/mesh_dir: exact-match %.4f < %.4f" % (name, ex_d, PARITY_MIN_EXACT))
    if mean_d > PARITY_MAX_MEAN:
      fails.append("%s/mesh_dir: mean|delta| %.3f > %.3f" % (name, mean_d, PARITY_MAX_MEAN))
    if expect_geo:
      if cov_d < MIN_COVERAGE:
        fails.append("%s: mesh_dir drew nothing (coverage %.3f)" % (name, cov_d))
    else:
      # all-culled: v_count==0 so EVERY over-dispatched slot must be guarded -> zero coverage.
      if cov_d > 0.0:
        fails.append("%s: mesh_dir rendered %.4f coverage on an all-culled view (guard leak)" % (name, cov_d))

    ex_i = None
    if ab.want_indirect:
      img_ind = ab.capture("mesh_ind", ab.parity)   # its own compaction dispatch runs in frame()
      ind_vis = ab.visible_chunks()[0]
      ind_args = ab.mesh_args()
      ex_i, mean_i, _cvi, cov_i = compare(img_vtx, img_ind)
      if ex_i < PARITY_MIN_EXACT:
        fails.append("%s/mesh_ind: exact-match %.4f < %.4f" % (name, ex_i, PARITY_MIN_EXACT))
      if mean_i > PARITY_MAX_MEAN:
        fails.append("%s/mesh_ind: mean|delta| %.3f > %.3f" % (name, mean_i, PARITY_MAX_MEAN))
      # the compaction is the WHOLE mechanism: it must select exactly the chunks the baseline
      # cull selects and publish them as the mesh grid's y count.
      if ind_vis != vis:
        fails.append("%s: compaction kept %d chunks, baseline cull kept %d" % (name, ind_vis, vis))
      if ind_args != (ab.vs.mps * ab.vs.mps, vis, 1):
        fails.append("%s: mesh command %s != expected (%d,%d,1)"
                     % (name, ind_args, ab.vs.mps * ab.vs.mps, vis))
      if expect_geo:
        if cov_i < MIN_COVERAGE:
          fails.append("%s: mesh_ind drew nothing (coverage %.3f)" % (name, cov_i))
      else:
        if cov_i > 0.0:
          fails.append("%s: mesh_ind rendered %.4f coverage on an all-culled view" % (name, cov_i))
        # the regression this path exists to kill: an all-culled view dispatches NOTHING.
        if ind_args[1] != 0:
          fails.append("%s: all-culled view still dispatches %d workgroup rows" % (name, ind_args[1]))

    rows.append((name, vis, total, cov_v, cov_m, exact, mean, ex_i, ex_d))

    if exact < PARITY_MIN_EXACT:
      fails.append("%s: exact-match %.4f < %.4f" % (name, exact, PARITY_MIN_EXACT))
    if mean > PARITY_MAX_MEAN:
      fails.append("%s: mean|delta| %.3f > %.3f" % (name, mean, PARITY_MAX_MEAN))
    if expect_geo:
      if cov_v < MIN_COVERAGE:
        fails.append("%s: baseline drew nothing (coverage %.3f)" % (name, cov_v))
      if cov_m < MIN_COVERAGE:
        fails.append("%s: mesh drew nothing (coverage %.3f)" % (name, cov_m))
    else:
      if cov_v > 0.0:
        fails.append("%s: baseline rendered %.4f coverage on an all-culled view" % (name, cov_v))
      if cov_m > 0.0:
        fails.append("%s: mesh rendered %.4f coverage on an all-culled view" % (name, cov_m))

  print("")
  print("  CORRECTNESS (parity %dx%d):" % (ab.parity.w, ab.parity.h))
  hdr = "  view | chunks | cover vtx/mesh | exact  mean | exact_d"
  if ab.want_indirect:
    hdr += " | exact_i"
  print(hdr)
  for (name, vis, total, cov_v, cov_m, exact, mean, ex_i, ex_d) in rows:
    line = ("  %-4s | %3d/%-3d |  %.3f / %.3f | %.4f %.3f | %.4f"
            % (name, vis, total, cov_v, cov_m, exact, mean, ex_d))
    if ab.want_indirect:
      line += " | %.4f" % (ex_i if ex_i is not None else float("nan"))
    print(line)
  return fails, rows


def run_performance(ab, args):
  """MESHPERF legs. Returns (emitted, fails):
     emitted -> True if MESHPERF lines were printed (calibration passed).
     fails   -> hard timing-artifact failures (negative/zero timings) — these DO
                fail the gate; a calibration refusal does NOT (it is correct under load).
  """
  fails = []
  res = "%dx%d" % (ab.perf.w, ab.perf.h)

  # ---- VSYNC-FREE / LOAD GUARD -------------------------------------------------
  fps = ab.calibration_fps(ab.perf, frames=args.calib_frames)
  passed = fps >= args.calib_min_fps
  print("")
  print("  MESHPERF_CALIBRATION res=%s fps=%.1f threshold=%.1f result=%s"
        % (res, fps, args.calib_min_fps, "PASS" if passed else "FAIL"))
  if not passed:
    # Refuse to measure. Loud, named, NO MESHPERF lines. Correct behavior under load.
    print("  MESHPERF ABORT reason=paced_or_overloaded fps=%.1f min=%.1f "
          "(offscreen is unpaced; a sub-floor rate means the box is paced or overloaded "
          "— refusing to publish timings)" % (fps, args.calib_min_fps))
    return False, fails

  # ---- accounting header -------------------------------------------------------
  print("")
  print("  ACCOUNTING: vtx = reset/cull/sort/finalize dispatch (submit+wait) + indirect draw")
  print("              frame ; mesh = fixed-grid mesh-task draw frame, NO compute ; mesh_ind =")
  print("              ONE compaction dispatch (submit+wait) + indirect mesh-task draw frame")
  print("              (the compaction is mode 2's own work, charged to mesh_ind). No HUD/stats")
  print("              passes in this synthetic test. ratio = mesh_ms / vtx_ms, ratio_ind =")
  print("              mesh_ind_ms / vtx_ms (< 1.0 => faster than baseline). Each sample is one")
  print("              FULL offscreen frame including its completion fence wait.")

  for (name, eye, tgt) in PERF_VANTAGES:
    ab.set_view(eye, tgt, ab.perf)
    v_mean, v_p50, v_p95, v_min = ab.time_leg("vtx",  ab.perf, frames=args.frames)
    m_mean, m_p50, m_p95, m_min = ab.time_leg("mesh", ab.perf, frames=args.frames)
    legs = [("vtx", v_min, v_mean, v_p95), ("mesh", m_min, m_mean, m_p95)]
    i_mean = i_p50 = i_p95 = None
    if ab.want_indirect:
      i_mean, i_p50, i_p95, i_min = ab.time_leg("mesh_ind", ab.perf, frames=args.frames)
      legs.append(("mesh_ind", i_min, i_mean, i_p95))

    # HARD FAIL on any non-positive timing (owner: reason=timing_artifact).
    for lbl, mn, mean_, p95 in legs:
      for suf, val in (("min", mn), ("mean", mean_), ("p95", p95)):
        if val <= 0.0:
          fails.append("%s: %s_%s=%.6f <= 0 (timing_artifact)" % (name, lbl, suf, val))

    ratio = (m_mean / v_mean) if v_mean > 0.0 else 0.0
    line = ("  MESHPERF vantage=%s res=%s frames=%d "
            "vtx_ms_mean=%.4f vtx_ms_p50=%.4f vtx_ms_p95=%.4f "
            "mesh_ms_mean=%.4f mesh_ms_p50=%.4f mesh_ms_p95=%.4f ratio=%.4f"
            % (name, res, args.frames,
               v_mean, v_p50, v_p95, m_mean, m_p50, m_p95, ratio))
    if ab.want_indirect:
      ratio_ind = (i_mean / v_mean) if v_mean > 0.0 else 0.0
      line += (" mesh_ind_ms_mean=%.4f mesh_ind_ms_p50=%.4f mesh_ind_ms_p95=%.4f ratio_ind=%.4f"
               % (i_mean, i_p50, i_p95, ratio_ind))
    print(line)

  return True, fails

################################################################################
# MSAA PER-SAMPLE SURCHARGE (gate leg) + the two upstream reproducers.
################################################################################

def _vantage(name):
  for entry in PERF_VANTAGES:
    if entry[0] == name:
      return entry
  raise SystemExit("unknown vantage %r (have: %s)"
                   % (name, ", ".join(v[0] for v in PERF_VANTAGES)))


def _msaa_available(ab, samples):
  """(ok, reason). Below the device ceiling only — the RtGroup ctor throws rather than
  handing back a quieter target, so a leg either measures what it asked for or SKIPs."""
  devmax = int(ab.ctx.msaa_max_samples)
  if samples > devmax:
    return False, "device msaa max %d < requested %dx" % (devmax, samples)
  return True, ""


def _proof_of_load(ab, samples):
  """Both paths must actually rasterize into a multisample target before any timing — an
  empty MSAA target would yield a gorgeous, meaningless surcharge. Small target, one frame
  per path, coverage only (MSAA resolves edges, so pixel parity does NOT apply).

  ALWAYS RGBA8: captureAsFormat cannot read back a half-float attachment (the readback path,
  not the render path — the timed legs still run on the configured format, and the clear-vs-draw
  guard below proves THOSE targets are doing work)."""
  small = ab.target(ab.parity.w, ab.parity.h, samples, "RGBA8")
  name, eye, tgt, _ = VIEWS[0]                # "wide": whole field on screen
  ab.set_view(eye, tgt, small)
  cov = {}
  for path in ("vtx", "mesh"):
    img = ab.capture(path, small)
    cov[path] = float((img[..., :3].astype(numpy.int16).sum(axis=2) > 0).mean())
  return cov


def run_msaa_surcharge(ab, args):
  """The per-sample mesh surcharge gate leg. See the MSAA block in the header for the
  metric and the platform-fence rationale. Returns a list of failures."""
  fails = []
  samples = int(args.msaa_samples)
  ok, why = _msaa_available(ab, samples)
  if not ok:
    print("")
    print("  MESHMSAA SKIP reason=%s" % why)
    return fails

  fmt = args.surcharge_format
  cov = _proof_of_load(ab, samples)
  print("")
  print("  MESHMSAA_PROOF_OF_LOAD msaa=%dx fmt=RGBA8 res=%dx%d coverage_vtx=%.3f coverage_mesh=%.3f"
        % (samples, ab.parity.w, ab.parity.h, cov["vtx"], cov["mesh"]))
  for path in ("vtx", "mesh"):
    if cov[path] < MIN_COVERAGE:
      fails.append("msaa %dx: %s drew nothing into the multisample target (coverage %.3f)"
                   % (samples, path, cov[path]))
  if fails:
    return fails

  name, eye, tgt = _vantage(args.surcharge_vantage)
  sw, sh = _wh(args.surcharge_res)
  t1 = ab.target(sw, sh, 1, fmt)
  tN = ab.target(sw, sh, samples, fmt)
  ab.set_view(eye, tgt, tN)          # same w/h as t1 -> one camera serves both legs
  res = "%dx%d" % (sw, sh)
  f   = int(args.surcharge_frames)

  means = {}
  for lvl, target in ((1, t1), (samples, tN)):
    # clear-only floor on the SAME target: the timed legs must cost meaningfully more than an
    # empty frame, or they are not drawing into the target they claim to be measuring (the
    # coverage proof above cannot see the half-float targets — readback limitation).
    clear_mean = ab.time_leg("mesh", target, frames=max(8, f // 8), draw_only_clear=True)[0]
    v_mean, _v50, _v95, v_min = ab.time_leg("vtx",  target, frames=f)
    m_mean, _m50, _m95, m_min = ab.time_leg("mesh", target, frames=f)
    for lbl, val in (("vtx_min", v_min), ("vtx_mean", v_mean),
                     ("mesh_min", m_min), ("mesh_mean", m_mean)):
      if val <= 0.0:
        fails.append("msaa %dx: %s=%.6f <= 0 (timing_artifact)" % (lvl, lbl, val))
    for lbl, val in (("vtx", v_mean), ("mesh", m_mean)):
      if val <= clear_mean * 1.2:
        fails.append("msaa %dx fmt=%s: %s leg %.4fms is not above the clear-only floor %.4fms "
                     "(the timed target is not drawing)" % (lvl, fmt, lbl, val, clear_mean))
    means[lvl] = (v_mean, m_mean)
    print("  MESHMSAA vantage=%s res=%s fmt=%s msaa=%d frames=%d vtx_ms_mean=%.4f mesh_ms_mean=%.4f ratio=%.4f"
          % (name, res, fmt, lvl, f, v_mean, m_mean, (m_mean / v_mean) if v_mean > 0.0 else 0.0))
  if fails:
    return fails

  ratio_1x = means[1][1] / means[1][0]
  ratio_Nx = means[samples][1] / means[samples][0]
  surcharge = ratio_Nx / ratio_1x if ratio_1x > 0.0 else 0.0

  plat        = "darwin" if sys.platform == "darwin" else "other"
  baseline    = SURCHARGE_BASELINE[plat]
  fence       = baseline * (1.0 + SURCHARGE_BAND)
  improved_at = baseline * (1.0 - SURCHARGE_BAND)
  result = "PASS"
  if surcharge > fence:
    result = "FAIL"
    fails.append("msaa surcharge %.3f > %s fence %.3f (recorded baseline %.3f +%.0f%%; "
                 "ratio_1x=%.3f ratio_%dx=%.3f)"
                 % (surcharge, plat, fence, baseline, SURCHARGE_BAND * 100.0,
                    ratio_1x, samples, ratio_Nx))
  elif surcharge < improved_at:
    # an improvement must never redden the fleet — it asks for a re-record instead.
    result = "IMPROVED"
  print("  MESHMSAA_SURCHARGE vantage=%s res=%s fmt=%s msaa=%d ratio_1x=%.4f ratio_%dx=%.4f "
        "surcharge=%.4f baseline=%.4f fence=%.4f platform=%s result=%s"
        % (name, res, fmt, samples, ratio_1x, samples, ratio_Nx, surcharge, baseline, fence,
           plat, result))
  if result == "IMPROVED":
    print("  MESHMSAA_SURCHARGE %s dropped clear of its recorded band: measured %.3f < %.3f. "
          "Re-measure (>=5 full gate runs) and re-record SURCHARGE_BASELINE[%r] to lock the gain in."
          % (plat, surcharge, improved_at, plat))
  return fails

################################################################################

def run_payload_cliff(app, args, ab0, want_indirect, parity_wh, perf_wh):
  """PAYLOAD CLIFF FENCE — one measurement, one platform-selected constant. See the header block.

  Measures mesh_ms at the SHIPPED meshlet on the multisampled 2x RGBA16F + Z32F set and compares
  it to the recorded baseline for this platform. Returns a list of failures."""
  samples = int(args.msaa_samples)
  ok, why = _msaa_available(ab0, samples)
  if not ok:
    print("")
    print("MESHCLIFF SKIP reason=%s" % why)
    return []
  w, h = _wh(args.sweep_res)
  fmt  = args.surcharge_format
  na   = CLIFF_NATTACH
  f    = int(args.cliff_frames)
  vname, eye, tgt = _vantage(args.surcharge_vantage)
  # the fence is about the DEFAULT payload; --meshlet must not be able to redefine it
  if ab0.vs.meshlet == SHIPPED_MESHLET:
    ab = ab0
    fresh = False
  else:
    ab = TerrainAB(app, parity_wh, perf_wh, want_indirect, meshlet=SHIPPED_MESHLET, mrt=True)
    fresh = True
  target = ab.target(w, h, samples, fmt, na)
  clear, v, m = _sweep_legs(ab, target, eye, tgt, f, na > 1)
  plat     = "darwin" if sys.platform == "darwin" else "other"
  baseline = CLIFF_BASELINE_MS[plat]
  fence    = CLIFF_FENCE[plat]
  ratio    = (m / baseline) if baseline > 0.0 else 0.0
  bad      = ratio > fence
  print("")
  print("PAYLOAD CLIFF FENCE: mesh cost at the SHIPPED meshlet vs its recorded baseline")
  print("  res=%dx%d vantage=%s frames=%d target=%dx %s + Z32F msaa=%dx meshlet=%d "
        "(%d verts / %d prims, %d workgroups)"
        % (w, h, vname, f, na, fmt, samples, ab.vs.meshlet, ab.vs.mesh_maxvtx, ab.vs.mesh_maxprim,
           ab.groups[0] * ab.groups[1] * ab.groups[2]))
  print("  MESHCLIFF res=%dx%d fmt=%s nattach=%d msaa=%d meshlet=%d frames=%d clear_ms=%.4f "
        "vtx_ms=%.4f mesh_ms=%.4f baseline_ms=%.4f ratio=%.4f fence=%.2f platform=%s result=%s"
        % (w, h, fmt, na, samples, ab.vs.meshlet, f, clear, v, m, baseline, ratio, fence, plat,
           "FAIL" if bad else "PASS"))
  if fresh:
    del ab
  if bad:
    return ["payload cliff: mesh_ms=%.4f at meshlet %d is %.3fx the recorded %s baseline "
            "%.4fms (fence %.2f) — the tile-contention cliff has been re-crossed"
            % (m, SHIPPED_MESHLET, ratio, plat, baseline, fence)]
  return []


def reproduce_surcharge(ab, args):
  """UPSTREAM ARTIFACT (MoltenVK defect 1): mesh pipelines in a multisampled render pass.
  Sweeps sample count x resolution for BOTH pipelines over identical geometry and prints
  the slope table. No verdict, no fence — a maintainer reads the numbers."""
  f = int(args.reproduce_frames)
  levels = [n for n in REPRO_MSAA_LEVELS if _msaa_available(ab, n)[0]]
  print("")
  print("REPRODUCE: mesh-pipeline per-sample surcharge")
  print("  geometry: %d chunks x %d meshlets, identical SSBO + shader text for both pipelines"
        % (ab.vs.nchunk, ab.vs.mps * ab.vs.mps))
  print("  vtx  = SSBO-pull vertex pipeline, non-indexed drawIndirect (%d verts/chunk)" % ab.vs.vpc)
  print("  mesh = taskless VK_EXT_mesh_shader pipeline, direct drawMeshTasks, no compute")
  print("  each cell: mean wall ms over %d full offscreen frames (submit + completion fence)" % f)
  print("  color format = %s (what the engine multisamples) ; device msaa max = %dx ; levels swept = %s"
        % (args.surcharge_format, ab.ctx.msaa_max_samples, levels))
  print("")
  print("  %-11s %-5s %10s %10s %8s  %s" % ("res", "msaa", "vtx_ms", "mesh_ms", "ratio", "vs 1x: vtx / mesh"))
  vname, eye, tgt = _vantage(args.surcharge_vantage)
  for (w, h) in REPRO_RESOLUTIONS:
    base = None
    for lvl in levels:
      target = ab.target(w, h, lvl, args.surcharge_format)
      ab.set_view(eye, tgt, target)
      v_mean = ab.time_leg("vtx",  target, frames=f)[0]
      m_mean = ab.time_leg("mesh", target, frames=f)[0]
      if base is None:
        base = (v_mean, m_mean)
      print("  %-11s %-5s %10.4f %10.4f %8.4f  %5.2fx / %5.2fx"
            % ("%dx%d" % (w, h), "%dx" % lvl, v_mean, m_mean, m_mean / v_mean,
               v_mean / base[0], m_mean / base[1]))
    print("")
  print("  READ THIS AS: the 'vs 1x' columns are each pipeline's own MSAA cost multiplier over")
  print("  identical geometry. They do NOT have to match each other — the two pipelines are")
  print("  bound by different things (the vtx path re-decodes every corner ~6x, the mesh path")
  print("  emits each corner once), so a gap between the columns on ONE machine proves nothing.")
  print("  The evidence is the SAME TABLE from a second platform: run it on a discrete GPU and")
  print("  compare the mesh column against the mesh column. Measured jul26: at 3840x2160/4x the")
  print("  mesh multiplier is 1.84x on MoltenVK/M3-Ultra and 1.92x on NVIDIA/3090 — i.e. the mesh")
  print("  pipeline's per-sample behaviour is NOT the outlier; the vtx baseline's is (1.11x mac,")
  print("  1.41x NVIDIA). Any upstream claim must survive that comparison.")


def reproduce_indirect(ab, args):
  """UPSTREAM ARTIFACT (MoltenVK defect 2): vkCmdDrawMeshTasksIndirectEXT against an
  SSBO-bound pipeline. Sweeps draw count (per-call linearity) and resolution (the cost is
  resolution-independent, so it is not rasterization), with the SAME pipeline drawn via the
  DIRECT entry point as the control."""
  if not ab.want_indirect:
    print("")
    print("REPRODUCE-INDIRECT SKIP: device has no vkCmdDrawMeshTasksIndirectEXT")
    return
  f = int(args.reproduce_frames)
  print("")
  print("REPRODUCE: drawMeshTasksIndirect per-call cost (SSBO-bound mesh pipeline)")
  print("  ALL legs render the SAME compacted visible-chunk list produced by ONE inline")
  print("  compaction dispatch; the legs differ ONLY in the draw entry point and call count.")
  print("    compaction-only : inline compaction dispatch, ZERO draws         (the floor)")
  print("    mesh_ind xK     : + K x vkCmdDrawMeshTasksIndirectEXT (args from the SSBO)")
  print("    mesh_dir x1     : + 1 x vkCmdDrawMeshTasksEXT over the same list (CPU-sized grid)")
  print("  each cell: mean wall ms over %d full offscreen frames (submit + completion fence)" % f)
  print("")
  vname, eye, tgt = _vantage(args.surcharge_vantage)
  hdr = "  %-11s %12s" % ("res", "compact-only")
  for k in REPRO_DRAWCOUNTS:
    hdr += " %12s" % ("mesh_ind x%d" % k)
  hdr += " %12s %14s" % ("mesh_dir x1", "ms/ind-call")
  print(hdr)
  for (w, h) in REPRO_RESOLUTIONS:
    target = ab.target(w, h, 1, args.surcharge_format)
    ab.set_view(eye, tgt, target)
    floor = ab.time_leg("mesh_ind", target, frames=f, draws=0)[0]
    per_k = {}
    for k in REPRO_DRAWCOUNTS:
      per_k[k] = ab.time_leg("mesh_ind", target, frames=f, draws=k)[0]
    direct = ab.time_leg("mesh_dir", target, frames=f, draws=1)[0]
    ks = sorted(per_k)
    slope = ((per_k[ks[-1]] - per_k[ks[0]]) / float(ks[-1] - ks[0])) if len(ks) > 1 else 0.0
    row = "  %-11s %12.4f" % ("%dx%d" % (w, h), floor)
    for k in REPRO_DRAWCOUNTS:
      row += " %12.4f" % per_k[k]
    row += " %12.4f %14.4f" % (direct, slope)
    print(row)
  print("")
  print("  READ THIS AS: ms/ind-call is the marginal cost of ONE extra indirect mesh draw")
  print("  recorded into the same render pass. Compare it to the compaction-only floor (the")
  print("  same GPU work minus the draws) and to mesh_dir, which draws the SAME meshlets over")
  print("  the SAME SSBO through the DIRECT entry point. A per-call cost in the tens of")
  print("  milliseconds that does not move with resolution is a CPU-side stall in the indirect")
  print("  path, not rasterization work.")

################################################################################
# TILE-CONTENTION SWEEPS (manual artifacts, no verdict): attachment weight and mesh payload.
################################################################################

def _sweep_legs(ab, target, eye, tgt, frames, mrt):
  """(clear_ms, vtx_ms, mesh_ms) on one target. The clear-only floor rides along in every row:
  a leg that does not clear the floor is not drawing into the target it claims to measure."""
  ab.set_view(eye, tgt, target)
  sfx = "_mrt" if mrt else ""
  clear = ab.time_leg("mesh" + sfx, target, frames=frames, draw_only_clear=True)[0]
  v     = ab.time_leg("vtx" + sfx,  target, frames=frames)[0]
  m     = ab.time_leg("mesh" + sfx, target, frames=frames)[0]
  return clear, v, m


def sweep_attachments(ab, args):
  """AXIS (a): attachment weight at fixed geometry/payload. If the mesh:vtx surcharge grows with
  attachment bytes/px at Nx (and stays flat at 1x, and does not track for vtx alone), tile memory
  shared between the attachment set and the mesh stage's output payload is implicated."""
  samples = int(args.msaa_samples)
  ok, why = _msaa_available(ab, samples)
  if not ok:
    print("")
    print("SWEEPATTACH SKIP reason=%s" % why)
    return
  w, h = _wh(args.sweep_res)
  f = int(args.sweep_frames)
  vname, eye, tgt = _vantage(args.surcharge_vantage)
  print("")
  print("SWEEP-ATTACH: mesh:vtx ratio vs attachment weight (tile-contention axis a)")
  print("  res=%dx%d vantage=%s frames=%d msaa levels=1,%d ; payload fixed at meshlet=%d "
        "(%d verts / %d prims per workgroup, %d workgroups)"
        % (w, h, vname, f, samples, ab.vs.meshlet, ab.vs.mesh_maxvtx, ab.vs.mesh_maxprim,
           ab.groups[0] * ab.groups[1] * ab.groups[2]))
  print("  every attachment is WRITTEN by the fragment stage (2xMRT legs use the _mrt techniques)")
  print("")
  print("  %-16s %5s %8s %9s %9s %9s %8s" % ("attachments", "msaa", "B/px", "clear_ms",
                                             "vtx_ms", "mesh_ms", "ratio"))
  for (fmt, na) in SWEEP_ATTACH_SETS:
    ratios = {}
    for lvl in (1, samples):
      target = ab.target(w, h, lvl, fmt, na)
      clear, v, m = _sweep_legs(ab, target, eye, tgt, f, na > 1)
      ratios[lvl] = (m / v) if v > 0.0 else 0.0
      flag = "" if (m > clear * 1.2 and v > clear * 1.2) else "  <-- BELOW CLEAR FLOOR"
      print("  %-16s %5s %8d %9.4f %9.4f %9.4f %8.4f%s"
            % ("%dx %s" % (na, fmt), "%dx" % lvl, target.bytes_per_px, clear, v, m,
               ratios[lvl], flag))
    surcharge = (ratios[samples] / ratios[1]) if ratios[1] > 0.0 else 0.0
    print("  SWEEPATTACH_SURCHARGE attachments=%dx%s bytes_px_1x=%d bytes_px_%dx=%d "
          "ratio_1x=%.4f ratio_%dx=%.4f surcharge=%.4f platform=%s"
          % (na, fmt, (FMT_BYTES[fmt] * na + 4), samples, (FMT_BYTES[fmt] * na + 4) * samples,
             ratios[1], samples, ratios[samples], surcharge,
             "darwin" if sys.platform == "darwin" else "other"))
    print("")
  print("  READ THIS AS: surcharge rising monotonically with attachment bytes/px CONFIRMS tile")
  print("  contention (and gives its slope); a flat surcharge column KILLS the hypothesis — the")
  print("  attachment set would then not be the missing variable between synthetic and real pass.")


def sweep_payload(app, args, ab0, want_indirect, parity_wh, perf_wh):
  """AXIS (b): mesh-stage output payload at fixed attachment set. Smaller meshlets cover the SAME
  terrain area with more, lighter workgroups. Cost falling as payload shrinks confirms contention
  from the other side and sizes the reshape fix; cost flat/rising says the payload is not the lever.
  Targets are built ONCE and shared across the per-meshlet programs (same context)."""
  samples = int(args.msaa_samples)
  ok, why = _msaa_available(ab0, samples)
  if not ok:
    print("")
    print("SWEEPPAYLOAD SKIP reason=%s" % why)
    return
  w, h = _wh(args.sweep_res)
  f = int(args.sweep_frames)
  fmt = args.surcharge_format
  na  = int(args.sweep_payload_attach)
  vname, eye, tgt = _vantage(args.surcharge_vantage)
  levels = [1, samples]
  targets = {lvl: ab0.target(w, h, lvl, fmt, na) for lvl in levels}
  meshlets = [int(x) for x in args.sweep_meshlets.split(",")]
  print("")
  print("SWEEP-PAYLOAD: mesh cost vs per-workgroup output payload (tile-contention axis b)")
  print("  res=%dx%d vantage=%s frames=%d target=%dx %s + Z32F ; msaa levels=%s"
        % (w, h, vname, f, na, fmt, ",".join(str(l) for l in levels)))
  print("  every row covers the SAME terrain (%d chunks of %d) — only the meshlet subdivision moves"
        % (ab0.vs.nchunk, CHUNK))
  print("")
  print("  %-8s %6s %6s %7s %8s %5s %9s %9s %9s %8s"
        % ("meshlet", "verts", "prims", "wg_inv", "wgroups", "msaa", "clear_ms", "vtx_ms",
           "mesh_ms", "ratio"))
  for ml in meshlets:
    if ml == ab0.vs.meshlet:
      ab = ab0
      fresh = False
    else:
      ab = TerrainAB(app, parity_wh, perf_wh, want_indirect, meshlet=ml, mrt=True)
      fresh = True
    wg = ab.groups[0] * ab.groups[1] * ab.groups[2]
    for lvl in levels:
      clear, v, m = _sweep_legs(ab, targets[lvl], eye, tgt, f, na > 1)
      flag = "" if (m > clear * 1.2 and v > clear * 1.2) else "  <-- BELOW CLEAR FLOOR"
      print("  %-8d %6d %6d %7d %8d %5s %9.4f %9.4f %9.4f %8.4f%s"
            % (ml, ab.vs.mesh_maxvtx, ab.vs.mesh_maxprim, ab.vs.mesh_wg, wg, "%dx" % lvl,
               clear, v, m, (m / v) if v > 0.0 else 0.0, flag))
    if fresh:
      del ab
    print("")
  print("  READ THIS AS: the vtx column is the control — it does not know the meshlet size, so any")
  print("  movement there is drift, not signal. The mesh column at %dx is the measurement." % samples)


################################################################################

def main():
  args = parse_args()
  parity_wh = _wh(args.parity_res)
  perf_wh   = _wh(args.res)

  code = 1
  with headless_app(subsystems=['opq', 'core', 'gpu', 'lev2']) as app:
    if not app.ctx.supports_mesh_shader:
      print("SKIP: device has no VK_EXT_mesh_shader (terrain mesh path not exercised)")
      code = verdict(True, "terrain mesh-shader A/B SKIPPED — VK_EXT_mesh_shader unavailable")
      sys.exit(code)
    want_indirect = bool(app.ctx.supports_mesh_shader_indirect)
    if not want_indirect:
      print("SKIP-LEG: device has VK_EXT_mesh_shader but no vkCmdDrawMeshTasksIndirectEXT "
            "— running the two-way (baseline vs direct) only")

    sweeping = bool(args.sweep_attach or args.sweep_payload)
    # the cliff fence draws into the 2xMRT half-float set, so it needs the _mrt techniques too
    want_cliff = bool(not (args.no_perf or args.no_cliff or args.reproduce or args.reproduce_indirect))
    ab = TerrainAB(app, parity_wh, perf_wh, want_indirect, meshlet=args.meshlet,
                   mrt=(sweeping or want_cliff))
    gx, gy, gz = ab.groups
    print("terrain A/B: dim=%d extent=%.0fm chunk=%d -> %d chunks | meshlet=%d -> %d verts / %d prims"
          % (DIM, EXTENT, CHUNK, ab.vs.nchunk, ab.vs.meshlet, ab.vs.mesh_maxvtx, ab.vs.mesh_maxprim))
    print("  baseline draw: %d verts/chunk (non-indexed pull) + 4 compute passes" % ab.vs.vpc)
    print("  mesh draw    : fixed grid <%d,%d,%d> = %d workgroups of %d invocations, no compute"
          % (gx, gy, gz, gx * gy * gz, ab.vs.mesh_wg))
    if want_indirect:
      print("  mesh-ind draw: <%d, visible_chunks, 1> from the GPU-written command + 1 compaction dispatch"
            % gx)
    print("  parity res=%dx%d  perf res=%dx%d  perf frames/leg=%d  calib_min_fps=%.0f"
          % (parity_wh[0], parity_wh[1], perf_wh[0], perf_wh[1], args.frames, args.calib_min_fps))
    print("  device msaa max=%dx  platform=%s" % (app.ctx.msaa_max_samples, sys.platform))

    # ---- TILE-CONTENTION SWEEPS (measurement artifacts; NO TESTVERDICT) ----
    if sweeping:
      if args.sweep_attach:
        sweep_attachments(ab, args)
      if args.sweep_payload:
        sweep_payload(app, args, ab, want_indirect, parity_wh, perf_wh)
      print("")
      print("(sweep mode: measurement artifact only — no verdict is emitted)")
      sys.exit(0)

    # ---- REPRODUCER MODES (upstream artifacts; deliberately emit NO TESTVERDICT) ----
    if args.reproduce or args.reproduce_indirect:
      if args.reproduce:
        reproduce_surcharge(ab, args)
      if args.reproduce_indirect:
        reproduce_indirect(ab, args)
      print("")
      print("(reproducer mode: measurement artifact only — no verdict is emitted)")
      sys.exit(0)

    # ---- CORRECTNESS (trusted; drives TESTVERDICT) -----------------------------
    fails, rows = run_correctness(ab)

    # ---- PERFORMANCE (reworked MESHPERF) ---------------------------------------
    perf_fails = []
    if not args.no_perf:
      _emitted, perf_fails = run_performance(ab, args)

    # ---- MSAA PER-SAMPLE SURCHARGE (platform-fenced) ---------------------------
    msaa_fails = []
    if not (args.no_perf or args.no_surcharge):
      msaa_fails = run_msaa_surcharge(ab, args)

    # ---- PAYLOAD CLIFF FENCE (platform-fenced, shipped meshlet) ----------------
    cliff_fails = []
    if want_cliff:
      cliff_fails = run_payload_cliff(app, args, ab, want_indirect, parity_wh, perf_wh)

    # A timing_artifact is a real failure; a calibration refusal is not.
    fails = fails + perf_fails + msaa_fails + cliff_fails

    print("")
    detail = "terrain mesh-shader A/B meshlet=%d | " % ab.vs.meshlet + " ".join(
        ("%s:exact=%.4f exact_d=%.4f" % (r[0], r[5], r[8]))
        + ((" exact_i=%.4f" % r[7]) if r[7] is not None else "")
        for r in rows)
    code = verdict(not fails, detail if not fails else detail + " | " + "; ".join(fails))

  sys.exit(code)


main()
