cmake_minimum_required (VERSION 3.13.4)
include(orkid)
project (ork.lev2.test.aud.singularity CXX)

include_directories(AFTER ${SRCD} )

set(HARNESS_SRCS harness.cpp harness_midi.cpp harness_sequence.cpp)

function(setupEXE target sources)
  setupLev2EXE (${target} ${sources} ${HARNESS_SRCS} )
  target_link_libraries( ${target} LINK_PRIVATE rtmidi )
endfunction()

setupEXE(ork.test.lev2.aud.singularity.krzrom.exe main_krzrom.cpp )
setupEXE(ork.test.lev2.aud.singularity.cz1.bank.exe main_cz1_bank.cpp )
setupEXE(ork.test.lev2.aud.singularity.cz1.dco.exe main_cz1_dco.cpp)
setupEXE(ork.test.lev2.aud.singularity.cz1.dco.noisemod.exe main_cz1_dco_noisemod.cpp)
setupEXE(ork.test.lev2.aud.singularity.cz1.dco.playedit.exe main_cz1_playedit.cpp)
setupEXE(ork.test.lev2.aud.singularity.cz1.envelope.exe main_cz1_envelope.cpp)
setupEXE(ork.test.lev2.aud.singularity.cz1.bankprog.exe main_cz1_bankprog.cpp)
setupEXE(ork.test.lev2.aud.singularity.hybrid.exe main_hybrid.cpp)
setupEXE(ork.test.lev2.aud.singularity.cz1.benchmark.exe main_cz1_benchmark.cpp)
setupEXE(ork.test.lev2.aud.singularity.tx81z.op.exe main_tx81z_op.cpp)
setupEXE(ork.test.lev2.aud.singularity.tx81z.bank.exe main_tx81z_bank.cpp)
setupEXE(ork.test.lev2.aud.singularity.tx81z.bankprog.exe main_tx81z_bankprog.cpp)
setupEXE(ork.test.lev2.aud.singularity.serdestest-out.exe main_serdestest_out.cpp)
setupEXE(ork.test.lev2.aud.singularity.serdestest-inp.exe main_serdestest_inp.cpp)
