services:
  cdn:
    image: openresty/openresty:alpine
    container_name: ork-secure-cdn
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./nginx/auth.lua:/usr/local/openresty/nginx/auth.lua:ro
      - ./nginx/upload.lua:/usr/local/openresty/nginx/upload.lua:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - $CONTENT_PATH:/cdn/content:rw
      - ./keys:/cdn/keys:ro
      - .$LOGDIR:/var/log/nginx
    restart: unless-stopped
    networks:
      - ork-cdn-network
    # Run nginx in foreground and show logs on console
    command: ["/usr/local/openresty/bin/openresty", "-g", "daemon off;"]
    # Environment for better logging
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1

networks:
  ork-cdn-network:
    driver: bridge