////////////////////////////////////////////////////////////////
// Orkid Media Engine
// Copyright 1996-2023, Michael T. Mayers.
// Distributed under the MIT License.
// see license-mit.txt in the root of the repo, and/or https://opensource.org/license/mit/
////////////////////////////////////////////////////////////////

#pragma once

#include <functional>
#include <mutex>
#include <unordered_map>
#include <ork/lev2/gfx/gfxenv_enum.h> // For ETextureDest
#include <ork/lev2/gfx/gfxenv.h>
#include <ork/lev2/gfx/renderer/rendercontext.h>
#include <ork/lev2/gfx/shadman.h>
#include <ork/lev2/gfx/rasterstate.h>
#include <ork/kernel/varmap.inl>

namespace ork::lev2 {

struct FxPipeline;
using fxpipeline_ptr_t      = std::shared_ptr<FxPipeline>;
using pipelineance_constptr_t = std::shared_ptr<const FxPipeline>;

///////////////////////////////////////////////////////////////////////////////

/*enum FxStateBasePermutation { MONO = 0, //
                              STEREO, // 
                              PICK, // 
                              COUNT };*/

///////////////////////////////////////////////////////////////////////////////
// FxPipeline : instance of a material "class"
//  with independent parameter values
///////////////////////////////////////////////////////////////////////////////

// GATE 0 negative control: when armed, every stereo-selection entry point clears the
//  _stereo bit, collapsing a stereo pass onto its mono technique. Default off; one cached
//  read shared by all sites so they cannot disagree. Defined in fx_pipeline.cpp.
bool gate0ForceMonoTechnique();

struct FxPipelinePermutation {

  void dump() const;
  uint64_t genIndex() const;

  // EVERY field below must appear in genIndex(), or two permutations that differ only in it
  //  collide in FxPipelineCache::_lut and the second one silently gets the first one's
  //  pipeline. Bit map (see genIndex): 0 free | 1 _stereo | 2 _instanced | 3 _skinned |
  //  4 _is_picking | 5 _has_vtxcolors | 6 _is_alpha | 7 _is_vertex_ssbo |
  //  8 _instanced_matrices_only | 9 _is_impostor | 10 _is_mesh_shader | 11 _is_sun_cookie |
  //  16.. _rendering_model | _forced_technique folded in as a pointer.
  uint32_t _rendering_model = "FORWARD_PBR"_crcu;
  bool _stereo = false;
  bool _instanced = false;
  bool _skinned = false;
  bool _is_picking = false;
  bool _has_vtxcolors = false;
  bool _is_alpha = false;
  bool _is_vertex_ssbo = false;   // SSBO-sourced vertices -> FWD_SSBO_CUSTOM variant
  bool _instanced_matrices_only = false;  // instanced from a matrices-only dynamic block (no per-inst color)
  bool _is_impostor = false;      // LOD impostor: billboard VS + atlas-sampling surface -> FWD_SSBO_CUSTOM_IMPOSTOR
  bool _is_mesh_shader = false;   // geometry generated by a mesh stage -> FWD_SSBO_CUSTOM_MESH variant
  bool _is_sun_cookie = false;    // cloud-shadow fill pass -> alpha-only FWD_SUNCOOKIE variant

  fxtechnique_constptr_t _forced_technique = nullptr;

};

struct FxPipelinePermutationSet {
  void add(fxpipelinepermutation_constptr_t perm);
  std::unordered_set<fxpipelinepermutation_constptr_t> __permutations;
};

///////////////////////////////////////////////////////////////////////////////
struct FxPipelineNamedParamProviders;
using fxpipelinenamedparamproviders_ptr_t = std::shared_ptr<FxPipelineNamedParamProviders>;

struct FxPipelineProviderContext {
  FxPipelineProviderContext(const RenderContextInstData& rcid, 
                            const CompositingPassData& topCPD, 
                            FxInterface* fxi);
  const RenderContextInstData& _rcid;
  const RenderContextFrameData* _rcfd;
  FxInterface* _fxi;
  const CompositingPassData& _topCPD;
};
struct FxPipelineNamedParamProviders {

  static fxpipelinenamedparamproviders_ptr_t instance();
  FxPipelineNamedParamProviders();

  using provider_fn_t = std::function<void(const FxPipelineProviderContext&, fxparam_constptr_t)>;
  std::unordered_map<uint64_t,provider_fn_t> _providers;
};


///////////////////////////////////////////////////////////////////////////////

struct FxPipeline {

  using varval_t = varmap::VarMap::value_type;
  using statelambda_t = std::function<void(const RenderContextInstData& RCID)>;
  using varval_generator_t = std::function<varval_t()>;

  FxPipeline(const FxPipelinePermutation& config);
  void dump() const;

  int beginBlock(const RenderContextInstData& RCID);
  void endBlock(const RenderContextInstData& RCID);
  void bindParam(fxparam_constptr_t p, varval_t v);
  void bindUniformBuffer(fxuniformblock_constptr_t p, varval_t v);
  // byte_offset binds a SUB-RANGE of the buffer (descriptor reads [byte_offset, end)). The same buffer
  // bound at distinct offsets resolves to distinct descriptor sets — sub-range LOD draws bind one
  // OUT_M at per-tier offsets within a frame. Must satisfy minStorageBufferOffsetAlignment. 0 = whole.
  void bindStorage(fxparamstorageblock_constptr_t p, varval_t v, size_t byte_offset = 0);
  void wrappedDrawCall(const RenderContextInstData& RCID, void_lambda_t drawcall);

  void _set_typed_param(const RenderContextInstData& RCID, fxparam_constptr_t p, varval_t val);
  void _set_storage(const RenderContextInstData& RCID, fxparamstorageblock_constptr_t p, varval_t val, size_t byte_offset = 0);
  // E.6/2.12 — re-overlay the parent material's _bound_params when its stamp
  // moved (called at the top of beginBlock; O(1) compare when clean). Material
  // rebinds AFTER pipeline creation are therefore live on the next draw.
  void _syncMaterialParams();
  void addStateLambda(statelambda_t sl){_statelambdas.push_back(sl);}

  template <typename T>
  std::shared_ptr<T> sharedMaterialAs() const {
    return std::dynamic_pointer_cast<T>(_sharedMaterial);
  }

  GfxMaterial* _material_ptr = nullptr;
  uint64_t _bound_params_seen = 0; // last-synced GfxMaterial::_bound_params_stamp
  rasterstate_ptr_t _rasterstate = nullptr;
  material_ptr_t _sharedMaterial = nullptr;
  fxtechnique_constptr_t _technique = nullptr;
  const FxPipelinePermutation __permutation;
  std::unordered_map<fxparam_constptr_t, varval_t> _params;
  std::unordered_map<fxuniformblock_constptr_t, varval_t> _uniformbuffers;
  std::unordered_map<fxparamstorageblock_constptr_t, varval_t> _storages;
  std::unordered_map<fxparamstorageblock_constptr_t, size_t>   _storage_offsets; // sub-range byte offset (default 0)
  std::vector<statelambda_t> _statelambdas;
  fxparamstorageblock_constptr_t _parInstanceBlock = nullptr;
  svar64_t _impl;

  bool _debugBreak = false;
  bool _debugPrint = false;
  std::string _debugName;
  mutable std::string _debugText;
  varmap::varmap_ptr_t _vars;

};

struct FxPipelineCache {

  using cache_miss_fn_t = std::function<fxpipeline_ptr_t(const FxPipelinePermutation&)>;
  fxpipeline_ptr_t findPipeline(const RenderContextInstData& RCID) const;
  fxpipeline_ptr_t findPipeline(const FxPipelinePermutation& permu) const;
  cache_miss_fn_t _on_miss;
  mutable std::unordered_map<uint64_t,fxpipeline_ptr_t> _lut;
  svar64_t _impl;
};

template <typename MtlClass>
  struct FxPipelineCacheImpl{

  FxPipelineCacheImpl(){}

  fxpipelinecache_constptr_t getCache(const MtlClass* material){

    fxpipelinecache_constptr_t rval;

    std::lock_guard<std::mutex> lock(_mutex);

    auto it = _fxcachemap.find(material);
    if(it==_fxcachemap.end()){
      auto newcache = std::make_shared<FxPipelineCache>();
      newcache->_impl.set<const MtlClass*>(material);
      newcache->_on_miss = [=](const FxPipelinePermutation& permu) -> fxpipeline_ptr_t {
        auto pipe = MtlClass::_createFxPipeline(permu,material);
        // generic material backref (rebind propagation): creators that did not
        // set it (e.g. FreestyleMaterial) get it here, so material->bindParam()
        // reaches EVERY template-cached pipeline via _syncMaterialParams.
        if(pipe and (pipe->_material_ptr==nullptr))
          pipe->_material_ptr = (GfxMaterial*) material;
        return pipe;
      };
      rval = newcache;
      _fxcachemap[material] = newcache;
    }
    else{
      rval = it->second;
    }

    return rval;
  }

  //////////////////////////////////////////////////////////////////////////////
  // MANDATORY for every material class that instantiates this template: call
  // this from the class's DESTRUCTOR.
  //
  // The map is keyed by raw material pointer and the allocator reuses
  // addresses. Without eviction, a material constructed after an identically
  // sized predecessor died can land on that predecessor's address and inherit
  // its FxPipelineCache — whose pipelines hold a raw backref to the DEAD
  // material (FxPipeline::_material_ptr, and the state lambdas' captured raw
  // `mtl`) and go on re-binding its freed textures/buffers. That is a
  // use-after-free that surfaces as a GPU page fault / device-lost at the next
  // submit, not as a crash at the reuse site. Diagnosed on the sky IBL refilter
  // path, which rebuilt its filter material every cycle.
  //
  // The evicted cache is RETURNED rather than dropped here: its pipelines can
  // hold the last shared_ptr to GPU-owning binds (SSBOs bound via bindStorage),
  // so the caller decides the release timing — the owning Context's
  // delayed-destroy queue, never an arbitrary thread's stack.
  //////////////////////////////////////////////////////////////////////////////

  fxpipelinecache_ptr_t removeCache(const MtlClass* material){
    std::lock_guard<std::mutex> lock(_mutex);
    fxpipelinecache_ptr_t rval;
    auto it = _fxcachemap.find(material);
    if(it!=_fxcachemap.end()){
      rval = it->second;
      _fxcachemap.erase(it);
    }
    return rval;
  }

  // Guards both entry points: getCache runs on the render thread, but a
  // material can be destroyed on any thread that drops its last shared_ptr
  // (python GC, asset teardown), and that thread now mutates this map.
  std::mutex _mutex;
  std::unordered_map<const MtlClass*,fxpipelinecache_ptr_t> _fxcachemap;
};

// E.6/2.12 gate — rebind-propagation core selftest (no GPU); returns failure count.
int fxPipelineRebindSelfTest();

} // namespace ork::lev2
